### ISSUE TITLE
Config issue ?

### ISSUE THREAD

**Issue by ctjhoa-linagora** [zemirco/nghellostyle#1]
Hi guy,
I try to start a project with closure compiler too but i'm facing a problem.
I added a logProvider in config :

```
/**
 * Configuration function.
 *
 * @param {ng.$logProvider} $logProvider
 * @param {ui.router.$stateProvider} $stateProvider
 * @param {ui.router.$urlRouterProvider} $urlRouterProvider
 * @ngInject
 */
function config($logProvider, $stateProvider, $urlRouterProvider) {

  $logProvider.debugEnabled(true);
  $urlRouterProvider.otherwise('/first');

}
```

And that's fail angular bootstraping saying : 'Uncaught object' in loadModules.

Any ideas ?
Thanks

**Comment by ctjhoa-linagora** [comment]
NB: when I comment "$logProvider.debugEnabled(true);" the bootstraping is fine.

**Comment by ctjhoa-linagora** [comment]
It seems to be an issue with compilation_level flag. Downgrade it to SIMPLE_OPTIMIZATIONS fixed the issue.

**Comment by zemirco** [comment]
Glad you solved the issue!

**Comment by andreasgrimm** [comment]
hmm, with just SIMPLE_OPTIMIZATIONS you're bypassing all the closure compiler's good stuff, aren 't you?
check your built file, if it is still optimized the way you would it expect it to be!

**Comment by ctjhoa-linagora** [comment]
Yeah sure SIMPLE_OPTIMIZATIONS is not the golden fix. Maybe i'm gonna ask this issue in the closure compiler github repo for more details.
