### ISSUE TITLE
support for local development?

### ISSUE THREAD

**Issue by akonsu** [zemirco/nghellostyle#2]
Currently `index.html` references the minified script: https://github.com/zemirco/nghellostyle/blob/bbfaa312a6c7504a85f39edff4e8d7fd605b5ea5/app/index.html#L25, which makes it inconvenient to develop locally. I am looking for a way to reference non-minified scripts when I develop and only minify them when deploying. Do you have any recommendations?

**Comment by zemirco** [comment]
Check out [usemin](https://github.com/yeoman/grunt-usemin).
