### ISSUE TITLE
Real apps examples

### ISSUE THREAD

**Issue by ctjhoa-linagora** [zemirco/nghellostyle#3]
Hi all,
I would like to share with you some real apps based on this repo.

https://github.com/linagora/linshare-ui-upload-request
https://github.com/linagora/linshare-ui-upload-proposition

I think it's interesting for others to see full app with gulp + bower + closure compiler + angular
Tests are not implemented yet (yeah I know it''s bad :) )

**Comment by zemirco** [comment]
Cool, when you've added some tests I could mention your apps in the Readme.
